language: node_js

node_js:
  - 10
  - 8

before_script:
  - npm prune

script:
  - npm run test:single

jobs:
  include:
    - stage: npm release
      if: branch = master
      node_js: "8"
      script: npm run semantic-release
